version: 2
builds:
  - main: ./cmd/main.go
    id: "vault-eth-signer-plugin"
    binary: vault-eth-signer-plugin
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    hooks:
      post:
        - sh -c 'cosign sign-blob --output-signature dist/{{ .ProjectName }}_{{ .Version }}_{{ .Target }}.sig --output-bundle dist/{{ .ProjectName }}_{{ .Version }}_{{ .Target }}.bundle {{ .Path }}'

archives:
  - id: "vault-eth-signer-plugin"
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    files:
      - dist/*.sig
      - dist/*.bundle

checksum:
  name_template: 'checksums.txt'

release:
  extra_files:
    - glob: dist/*.sig
    - glob: dist/*.bundle

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
