name: goreleaser

on:
  release:
    types: [published]

permissions:
  contents: write
  id-token: write  # Required for keyless signing

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.4.0

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Updated verification step
      - name: Verify signatures
        run: |
          for file in dist/vault-eth-signer-plugin_linux_amd64_v1/vault-eth-signer-plugin; do
            if [ -f "$file" ]; then
              echo "Verifying $file"
              cosign verify-blob --bundle "${file}.bundle" \
                --certificate-identity "https://github.com/${{ github.repository }}" \
                --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
                "$file"
            fi
          done
